const { throwError } = require("../../utils/helper")

const getAll = async () => {
    try{
        // const events = 
    }catch(err){
        throwError(err)
    }
}